# Generated by Django 3.2.3 on 2021-05-30 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0002_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_name', models.CharField(max_length=52, unique=True, verbose_name='Name')),
                ('active', models.BooleanField(default=True)),
                ('file', models.FileField(upload_to='uploads/%Y/%m/%d/')),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.class')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.subject')),
            ],
        ),
    ]
