# Generated by Django 3.2.3 on 2021-05-30 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0003_studymaterial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studymaterial',
            old_name='chapter_name',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='studymaterial',
            name='file',
            field=models.FileField(upload_to='uploads/'),
        ),
    ]
