# Generated by Django 3.2.3 on 2021-06-01 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=52, unique=True, verbose_name='Name')),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=2000, verbose_name='Name')),
                ('option1', models.CharField(max_length=500, verbose_name='option1')),
                ('option2', models.CharField(max_length=500, verbose_name='option2')),
                ('option3', models.CharField(max_length=500, verbose_name='option3')),
                ('option4', models.CharField(max_length=500, verbose_name='option4')),
                ('ans', models.CharField(max_length=500, verbose_name='ans')),
                ('active', models.BooleanField(default=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizzes.quiz')),
            ],
        ),
    ]
